apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: console-serving-cert
  name: cost-mgmt-proxy
  namespace: costmanagement-metrics-operator
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app: cost-mgmt-proxy